# Basic Site Settings
title: Sania's Portfolio
description: Data Analytics Portfolio showcasing projects and skills
baseurl: "/Sania-s_Portfolio"
url: "https://sania3fat.github.io"

# Author Information
author:
  name: Sania Fatima
  title: Business Analytics Graduate | Data Analyst
  email: sfatima3@kent.edu
  github: sania3fat

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  class_projects:
    output: true
    permalink: /class-projects/:name

# Default Settings
defaults:
  - scope:
      path: ""
      type: "class_projects"
    values:
      layout: "project"

# Navigation
navigation:
  - title: Home
    url: /
  - title: Class Projects
    url: /class-projects
  - title: Featured Projects
    url: /projects
  - title: About
    url: /about

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md
