# Basic Site Settings
title: Sania's Portfolio
description: Data Analytics Portfolio showcasing academic and professional projects
baseurl: "/Sania-s_Portfolio"
url: "https://sania3fat.github.io"

# Author Information
author:
  name: Sania Fatima
  title: Business Analytics Graduate | Data Analyst
  email: sfatima3@kent.edu
  github: sania3fat
  linkedin: "https://www.linkedin.com/in/sania-fatima-a1a732277/"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  featured_projects:
    output: true
    permalink: /projects/:name
  class_projects:
    output: true
    permalink: /class-projects/:name

# Default Settings for Collections
defaults:
  - scope:
      path: ""
      type: "featured_projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "class_projects"
    values:
      layout: "project"

# Navigation
navigation:
  - title: Home
    url: /
  - title: Class Projects
    url: /class-projects
  - title: Featured Projects
    url: /projects
  - title: About
    url: /about

# Project Categories
project_categories:
  - data-analysis
  - machine-learning
  - visualization
  - database
  - statistics

# Technologies
technologies:
  programming:
    - Python
    - R
    - SQL
    - MATLAB
  visualization:
    - Tableau
    - Power BI
    - ggplot2
    - matplotlib
  tools:
    - Git
    - MS SQL Server
    - Jupyter Notebook
    - RStudio

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md
  - CHANGELOG.md
